aaronmicalbeck/project-one

index.html
=> HTML Skeleton

README.md
updated readME to reflect our MVP for project one.
=> https://github.com/aaronmicalbeck/project-one.git

assets/css/reset.css
Added and updated reset.css and added reset.css & style.css links in index.html head
=> added reset.css and style.css links in index.html

assets/css/style.css, index.html
Created buttons, centered objects and added style to the page.
=> Creates style and buttons

assets/css/style.css
Changed the header photo styling
=> Stops repeated header photo

assets/css/style.css, index.html
Maybe we want to do it for the table too
=> Added margins for input form

assets/css/style.css, index.html
=> Creates a new style sheet

assets/javascript/app.js, index.html
added javascript to take user input of city and state and use API to return latitude and longitude
=> added java to get user input lat/long values

assets/css/style.css, index.html
Made the jumbotron wording pop more.
=> creates a gradient for image and changed color of text

assets/javascript/app.js
Added click event on Submit button to run lat long API and then subsequently the GoogleMaps API.  GoogleMaps takes the lat and lon of the user input value and centers the map for now.
=> googlemaps API runs and takes lat/lon API

index.html
=> Deleted toast message

assets/javascript/app.js
foursquare API takes latitude and longitude params from user input and returns JSON object (console logs this)
=> foursquare api takes user input

assets/javascript/app.js
For loop runs through JSON that Foursquare returns and Google Maps applies markers to correspond.
=> foursquare app and google map API work together

assets/css/style.css, assets/javascript/app.js
=> changes the background of the jumbotron

assets/javascript/app.js
Table dynamically generates based on user input and yea
=> dynamically generated tabelzzz

assets/javascript/app.js
=> fixed double function problem

assets/javascript/app.js
when submit button is clicked, table refreshes
=> table refreshes each search

assets/javascript/app.js, index.html
=> Changes the styling of the table

assets/javascript/app.js
=> Resets the search and dynamically creates the table

index.html
=> Creates a copyright footer

assets/css/style.css, index.html
=> Makes the jumbotron responsive

assets/css/style.css, assets/javascript/app.js, index.html
Re-labeled a couple of elements/columns.  Cleaned up code a tad.  Added and cleaned up some comments. 
Most importantly: centered the forms for user input. Seems to be totally responsive now.
=> cleaned up code/centered forms/cleaned up comments

assets/css/style.css, index.html
=> Creates a fixed footer

index.html
Centered Open Map button in mobile responsive fashion
=> Open Map button inside jumbotron
